// src/App.tsx
import { useState, useEffect, useCallback, useRef } from 'react';
import { imageLoader, getRenderingEngine } from '@cornerstonejs/core';
import type { IStackViewport } from '@cornerstonejs/core';
import { initCornerstone } from './viewer/CornerstoneInit';
import DicomDropZone, { type LoadResult } from './viewer/DicomDropZone';
import ViewportGrid, { type ActiveToolName, type LayoutType, type OrientationMarkerType } from './viewer/ViewportGrid';
import Toolbar from './viewer/Toolbar';
import LoadingOverlay from './viewer/LoadingOverlay';
import MetadataPanel from './ui/MetadataPanel';
import SeriesBrowser from './ui/SeriesBrowser';
import ChatSidebar, { type ChatSidebarHandle } from './ui/ChatSidebar';
import SettingsPanel from './ui/SettingsPanel';
import DisclaimerModal from './ui/DisclaimerModal';
import LandingScreen from './ui/LandingScreen';
import type { AnatomicalPlane } from './dicom/orientationUtils';
import type { StudyMetadata } from './dicom/types';
import type { ProviderConfig, ViewportContext } from './llm/types';
import { useLLMChat, type SliceMapping } from './llm/useLLMChat';
import { createDefaultProviderConfig, migrateProviderConfig } from './llm/providerConfig';
import { logger } from './utils/logger';

const STORAGE_KEY = 'dicomassist-llm-config';

function loadConfig(): ProviderConfig {
  try {
    const saved = localStorage.getItem(STORAGE_KEY);
    if (saved) return migrateProviderConfig(JSON.parse(saved));
  } catch { /* ignore */ }
  return createDefaultProviderConfig();
}

function saveConfig(config: ProviderConfig) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(config));
}

export default function App() {
  const [disclaimerAccepted, setDisclaimerAccepted] = useState(false);
  const [ready, setReady] = useState(false);
  const [imageIds, setImageIds] = useState<string[]>([]);
  const [primaryAxis, setPrimaryAxis] = useState<AnatomicalPlane>('axial');
  const [orientation, setOrientation] = useState<AnatomicalPlane>('axial');
  const [activeTool, setActiveTool] = useState<ActiveToolName>('WindowLevel');
  const [layout, setLayout] = useState<LayoutType>('1x1');
  const [orientationMarkerType, setOrientationMarkerType] = useState<OrientationMarkerType>('cube');
  const [prefetchProgress, setPrefetchProgress] = useState({ loaded: 0, total: 0 });
  const [studyMetadata, setStudyMetadata] = useState<StudyMetadata | null>(null);
  const [showMetadata, setShowMetadata] = useState(false);
  const [showChat, setShowChat] = useState(false);
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [providerConfig, setProviderConfig] = useState<ProviderConfig>(loadConfig);
  const [showSeriesBrowser, setShowSeriesBrowser] = useState(false);
  const [activeSeriesUID, setActiveSeriesUID] = useState<string>('');
  const [invert, setInvert] = useState(false);
  const [flipH, setFlipH] = useState(false);
  const [flipV, setFlipV] = useState(false);
  const [cineEnabled, setCineEnabled] = useState(false);
  const resetRef = useRef<(() => void) | null>(null);
  const chatSidebarRef = useRef<ChatSidebarHandle>(null);

  const {
    messages,
    status,
    statusText,
    error,
    currentPlan,
    pipeline,
    startAnalysis,
    confirmPlan,
    cancelPlan,
    sendFollowUp,
    clearChat,
  } = useLLMChat(studyMetadata, providerConfig);

  useEffect(() => {
    initCornerstone().then(() => setReady(true));
  }, []);

  const handleFilesLoaded = useCallback((result: LoadResult) => {
    setImageIds(result.imageIds);
    setPrimaryAxis(result.primaryAxis);
    setOrientation(result.primaryAxis);
    setStudyMetadata(result.studyMetadata);
    setActiveSeriesUID(result.studyMetadata.primarySeriesUID);
    if (result.studyMetadata.series.length > 1) {
      setShowSeriesBrowser(true);
    }
  }, []);

  // Prefetch all images after they're set
  useEffect(() => {
    if (imageIds.length === 0) return;

    let cancelled = false;
    const total = imageIds.length;
    let loaded = 0;

    setPrefetchProgress({ loaded: 0, total });

    const BATCH_SIZE = 6;
    async function prefetch() {
      for (let i = 0; i < total; i += BATCH_SIZE) {
        if (cancelled) return;
        const batch = imageIds.slice(i, i + BATCH_SIZE);
        const promises = batch.map((id) =>
          imageLoader.loadAndCacheImage(id).catch(() => {})
        );
        await Promise.all(promises);
        loaded += batch.length;
        if (!cancelled) {
          setPrefetchProgress({ loaded: Math.min(loaded, total), total });
        }
      }
    }

    prefetch();

    return () => {
      cancelled = true;
    };
  }, [imageIds]);

  // Apply SelectionPlan to viewport (W/L + scroll + switch series if needed)
  useEffect(() => {
    if (!currentPlan || !studyMetadata) return;

    const targetSeries = studyMetadata.series.find(
      (s) => String(s.seriesNumber) === currentPlan.targetSeries,
    );

    // If the plan targets a different series, switch the viewport to it
    if (targetSeries) {
      const targetImageIds = targetSeries.slices.map((s) => s.imageId);
      if (targetImageIds.length > 0 && targetImageIds[0] !== imageIds[0]) {
        setImageIds(targetImageIds);
        // W/L and scroll will be applied after the viewport reloads with new imageIds
      }
      setActiveSeriesUID(targetSeries.seriesInstanceUID);
    }

    // Apply W/L and scroll (may run before or after series switch)
    let attempts = 0;
    const applyPlan = () => {
      try {
        const engine = getRenderingEngine('dicomRenderingEngine');
        if (!engine) {
          // Viewport not ready yet — retry
          if (attempts++ < 5) setTimeout(applyPlan, 200);
          return;
        }
        const viewport = engine.getViewport('CT_STACK') as IStackViewport | undefined;
        if (!viewport) {
          if (attempts++ < 5) setTimeout(applyPlan, 200);
          return;
        }

        const viewportIds = viewport.getImageIds();
        if (viewportIds.length === 0) {
          if (attempts++ < 5) setTimeout(applyPlan, 200);
          return;
        }

        const { windowCenter, windowWidth } = currentPlan;
        viewport.setProperties({ voiRange: { lower: windowCenter - windowWidth / 2, upper: windowCenter + windowWidth / 2 } });

        if (targetSeries) {
          const [rangeStart, rangeEnd] = currentPlan.sliceRange;
          const midInstance = Math.round((rangeStart + rangeEnd) / 2);
          // Find the slice closest to midInstance in the target series
          const sliceIdx = targetSeries.slices.findIndex((s) => s.instanceNumber >= midInstance);
          if (sliceIdx >= 0 && sliceIdx < viewportIds.length) {
            viewport.setImageIdIndex(sliceIdx);
          }
        }

        viewport.render();
      } catch {
        // viewport may not be ready yet — retry
        if (attempts++ < 5) setTimeout(applyPlan, 200);
      }
    };

    // Delay to let series switch + viewport setup take effect
    const timer = setTimeout(applyPlan, 300);
    return () => clearTimeout(timer);
  }, [currentPlan, studyMetadata]); // intentionally omitting imageIds to avoid loop

  // When plan arrives, ensure sidebar is open
  useEffect(() => {
    if (status === 'awaiting-confirmation') {
      setShowChat(true);
      setShowMetadata(false);
    }
  }, [status]);

  // Auto-open chat when analysis completes
  useEffect(() => {
    if (messages.length > 0 && status === 'idle') {
      setShowChat(true);
    }
  }, [messages.length, status]);

  // Keyboard shortcuts
  useEffect(() => {
    function handleKeyDown(e: KeyboardEvent) {
      const mod = e.metaKey || e.ctrlKey;

      if (mod && e.key === 'k') {
        e.preventDefault();
        if (imageIds.length > 0 && studyMetadata) {
          setShowChat(true);
          setShowMetadata(false);
          // Focus the input after the sidebar renders
          requestAnimationFrame(() => chatSidebarRef.current?.focusInput());
        }
      }

      if (e.key === 'Escape') {
        if (status === 'awaiting-confirmation') {
          cancelPlan();
        } else if (settingsOpen) {
          setSettingsOpen(false);
        }
      }
    }

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [imageIds.length, studyMetadata, settingsOpen, status, cancelPlan]);

  // Fall back to W/L if leaving MPR while Crosshairs is active
  useEffect(() => {
    if (layout !== 'mpr' && activeTool === 'Crosshairs') {
      setActiveTool('WindowLevel');
    }
  }, [layout, activeTool]);

  const handleReset = useCallback(() => {
    resetRef.current?.();
    setInvert(false);
    setFlipH(false);
    setFlipV(false);
    setCineEnabled(false);
  }, []);

  const handleAcceptDisclaimer = useCallback(() => {
    setDisclaimerAccepted(true);
  }, []);

  const handleConfigChange = useCallback((config: ProviderConfig) => {
    setProviderConfig(config);
    saveConfig(config);
  }, []);

  const handleStartAnalysis = useCallback((hint: string, options?: { surveyMode?: boolean }) => {
    // Capture current viewport position as context for slice selection
    let viewportContext: ViewportContext | undefined;
    try {
      const engine = getRenderingEngine('dicomRenderingEngine');
      const viewport = engine?.getViewport('CT_STACK') as IStackViewport | undefined;
      if (viewport && studyMetadata) {
        const sliceIndex = viewport.getCurrentImageIdIndex();
        // Find which series is currently displayed
        const currentIds = viewport.getImageIds();
        const currentSeries = studyMetadata.series.find((s) =>
          s.slices.length === currentIds.length && s.slices[0]?.imageId === currentIds[0],
        ) ?? studyMetadata.series.find((s) =>
          s.slices.some((sl) => sl.imageId === currentIds[0]),
        );
        if (currentSeries && sliceIndex >= 0 && sliceIndex < currentSeries.slices.length) {
          const slice = currentSeries.slices[sliceIndex];
          viewportContext = {
            currentInstanceNumber: slice.instanceNumber,
            currentZPosition: slice.imagePositionPatient[2],
            seriesNumber: String(currentSeries.seriesNumber),
            totalSlicesInSeries: currentSeries.slices.length,
          };
          logger.log('[DICOMassist] Viewport context:', viewportContext);
        }
      }
    } catch { /* viewport may not be ready */ }

    startAnalysis(hint, viewportContext, options);
  }, [startAnalysis, studyMetadata]);

  const navigateTargetRef = useRef<{ instanceNumber: number; imageId: string; seriesNumber: string } | null>(null);

  const handleNavigateToSlice = useCallback((mapping: SliceMapping) => {
    if (!studyMetadata || !currentPlan) return;

    // Use the mapping's seriesNumber (multi-series aware) to find the correct series
    const seriesNum = mapping.seriesNumber || currentPlan.targetSeries;
    const targetSeries = studyMetadata.series.find(
      (s) => String(s.seriesNumber) === seriesNum,
    );
    if (!targetSeries) return;

    // Check if we need to switch series first
    const needsSeriesSwitch = targetSeries.seriesInstanceUID !== activeSeriesUID;

    if (needsSeriesSwitch) {
      logger.log(`[Navigate] Switching from series ${activeSeriesUID} → ${targetSeries.seriesInstanceUID} (${targetSeries.seriesDescription})`);
      // Store the target so we can scroll after series loads
      navigateTargetRef.current = { instanceNumber: mapping.instanceNumber, imageId: mapping.imageId, seriesNumber: seriesNum };
      const targetImageIds = targetSeries.slices.map((s) => s.imageId);
      setImageIds(targetImageIds);
      setActiveSeriesUID(targetSeries.seriesInstanceUID);
      const plane = targetSeries.anatomicalPlane === 'oblique' ? 'axial' : targetSeries.anatomicalPlane;
      setPrimaryAxis(plane);
      setOrientation(plane);
      setLayout('1x1');
      return; // scrollToSlice will be called by the effect below once images load
    }

    // Already on the correct series — scroll directly
    scrollToSlice(mapping.instanceNumber, mapping.imageId, targetSeries);
  }, [studyMetadata, currentPlan, activeSeriesUID]);

  // After a series switch triggered by slice navigation, scroll to the target slice
  useEffect(() => {
    const target = navigateTargetRef.current;
    if (!target || !studyMetadata) return;

    const targetSeries = studyMetadata.series.find(
      (s) => String(s.seriesNumber) === target.seriesNumber,
    );
    if (!targetSeries || targetSeries.seriesInstanceUID !== activeSeriesUID) return;

    // Series is now active — try to scroll (with retries for viewport readiness)
    let attempts = 0;
    const tryScroll = () => {
      const success = scrollToSlice(target.instanceNumber, target.imageId, targetSeries);
      if (!success && attempts++ < 5) {
        setTimeout(tryScroll, 200);
      } else {
        navigateTargetRef.current = null;
      }
    };
    const timer = setTimeout(tryScroll, 100);
    return () => clearTimeout(timer);
  }, [activeSeriesUID, studyMetadata]);

  function scrollToSlice(
    instanceNumber: number,
    imageId: string,
    targetSeries: StudyMetadata['series'][number],
  ): boolean {
    try {
      const engine = getRenderingEngine('dicomRenderingEngine');
      if (!engine) return false;

      let viewport = engine.getViewport('CT_STACK') as IStackViewport | undefined;
      if (!viewport) {
        viewport = engine.getViewport('CT_SINGLE_VOL') as IStackViewport | undefined;
      }
      if (!viewport) return false;

      const viewportIds = viewport.getImageIds();
      if (viewportIds.length === 0) return false;

      // Strategy 1: Find by instance number in the target series metadata
      const sliceIdx = targetSeries.slices.findIndex(
        (s) => s.instanceNumber === instanceNumber,
      );
      if (sliceIdx >= 0 && sliceIdx < viewportIds.length) {
        logger.log(`[Navigate] Instance #${instanceNumber} → series index ${sliceIdx}`);
        viewport.setImageIdIndex(sliceIdx);
        viewport.render();
        return true;
      }

      // Strategy 2: Direct imageId match
      const exactIdx = viewportIds.indexOf(imageId);
      if (exactIdx >= 0) {
        logger.log(`[Navigate] Exact imageId match at index ${exactIdx}`);
        viewport.setImageIdIndex(exactIdx);
        viewport.render();
        return true;
      }

      // Strategy 3: Partial imageId match
      const partialIdx = viewportIds.findIndex(
        (id) => id.includes(imageId) || imageId.includes(id),
      );
      if (partialIdx >= 0) {
        logger.log(`[Navigate] Partial imageId match at index ${partialIdx}`);
        viewport.setImageIdIndex(partialIdx);
        viewport.render();
        return true;
      }

      logger.warn(`[Navigate] Failed to find slice for instance #${instanceNumber}`, {
        imageId,
        viewportIdCount: viewportIds.length,
      });
      return false;
    } catch {
      return false;
    }
  }

  const handleToggleMetadata = useCallback(() => {
    if (!studyMetadata) return;
    setShowMetadata((v) => {
      if (!v) setShowChat(false);
      return !v;
    });
  }, [studyMetadata]);

  const handleSelectSeries = useCallback((seriesUID: string) => {
    if (!studyMetadata || seriesUID === activeSeriesUID) return;
    const series = studyMetadata.series.find((s) => s.seriesInstanceUID === seriesUID);
    if (!series) return;
    setImageIds(series.slices.map((s) => s.imageId));
    setActiveSeriesUID(seriesUID);
    const plane = series.anatomicalPlane === 'oblique' ? 'axial' : series.anatomicalPlane;
    setPrimaryAxis(plane);
    setOrientation(plane);
    setLayout('1x1');
  }, [studyMetadata, activeSeriesUID]);

  if (!ready) {
    return (
      <>
        {!disclaimerAccepted && <DisclaimerModal onAccept={handleAcceptDisclaimer} />}
        <div className="flex items-center justify-center h-full text-neutral-500">
          Initializing viewer...
        </div>
      </>
    );
  }

  if (imageIds.length === 0) {
    return (
      <div className="h-full overflow-y-auto">
        {!disclaimerAccepted && <DisclaimerModal onAccept={handleAcceptDisclaimer} />}
        <LandingScreen>
          <DicomDropZone onFilesLoaded={handleFilesLoaded} />
        </LandingScreen>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full">
      <Toolbar
        activeTool={activeTool}
        onToolChange={setActiveTool}
        layout={layout}
        onLayoutChange={setLayout}
        onReset={handleReset}
        showSeriesBrowser={showSeriesBrowser}
        onToggleSeriesBrowser={studyMetadata && studyMetadata.series.length > 1 ? () => setShowSeriesBrowser((v) => !v) : undefined}
        showMetadata={showMetadata}
        onToggleMetadata={studyMetadata ? handleToggleMetadata : undefined}
        onOpenSpotlight={() => {
          setShowChat(true);
          setShowMetadata(false);
          requestAnimationFrame(() => chatSidebarRef.current?.focusInput());
        }}
        onOpenSettings={() => setSettingsOpen((v) => !v)}
        orientationMarkerType={orientationMarkerType}
        onOrientationMarkerTypeChange={setOrientationMarkerType}
        invert={invert}
        onInvertToggle={() => setInvert((v) => !v)}
        flipH={flipH}
        onFlipHToggle={() => setFlipH((v) => !v)}
        flipV={flipV}
        onFlipVToggle={() => setFlipV((v) => !v)}
        cineEnabled={cineEnabled}
        onCineToggle={() => setCineEnabled((v) => !v)}
      />
      <div className="flex-1 min-h-0 flex overflow-hidden">
        {showSeriesBrowser && studyMetadata && studyMetadata.series.length > 1 && (
          <SeriesBrowser
            metadata={studyMetadata}
            activeSeriesUID={activeSeriesUID}
            onSelectSeries={handleSelectSeries}
            onClose={() => setShowSeriesBrowser(false)}
          />
        )}
        <div className="flex-1 min-w-0 relative overflow-hidden">
          <div className="absolute inset-0">
            <ViewportGrid
              imageIds={imageIds}
              activeTool={activeTool}
              layout={layout}
              orientation={orientation}
              primaryAxis={primaryAxis}
              orientationMarkerType={orientationMarkerType}
              onResetRef={resetRef}
              invert={invert}
              flipH={flipH}
              flipV={flipV}
              cineEnabled={cineEnabled}
              studyMetadata={studyMetadata}
            />
          </div>
          <LoadingOverlay
            loaded={prefetchProgress.loaded}
            total={prefetchProgress.total}
          />
        </div>
        {showMetadata && studyMetadata && (
          <MetadataPanel
            metadata={studyMetadata}
            activeSeriesUID={activeSeriesUID}
            onClose={() => setShowMetadata(false)}
          />
        )}
        {showChat && (
          <ChatSidebar
            ref={chatSidebarRef}
            messages={messages}
            status={status}
            statusText={statusText}
            error={error}
            pipeline={pipeline}
            currentPlan={currentPlan}
            studyMetadata={studyMetadata}
            onConfirmPlan={confirmPlan}
            onCancelPlan={cancelPlan}
            onStartAnalysis={handleStartAnalysis}
            onSendFollowUp={sendFollowUp}
            onClear={clearChat}
            onClose={() => setShowChat(false)}
            onNavigateToSlice={handleNavigateToSlice}
          />
        )}
      </div>

      {/* Overlays */}
      <SettingsPanel
        open={settingsOpen}
        onClose={() => setSettingsOpen(false)}
        config={providerConfig}
        onConfigChange={handleConfigChange}
      />
    </div>
  );
}

// src/App.vue
<script setup lang="ts">
import { computed, defineAsyncComponent, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import type { StudyMetadata } from './dicom/types';
import { initCornerstone } from './viewer/CornerstoneInit';
import { createDefaultProviderConfig, migrateProviderConfig } from './llm/providerConfig';
import type { ProviderConfig, ViewportContext } from './llm/types';
import { useLLMChat, type SliceMapping } from './llm/useLLMChat';
import type { LoadResult } from './composables/useDicomStudyLoader';
import LandingScreen from './components/LandingScreen.vue';
import type { ViewerLayout, ViewerTool } from './components/DicomViewer.vue';
import ToolbarPanel from './components/ToolbarPanel.vue';
import MetadataPanel from './components/MetadataPanel.vue';
import ChatSidebar from './components/ChatSidebar.vue';
import SettingsPanel from './components/SettingsPanel.vue';

const STORAGE_KEY = 'dicomassist-llm-config';
const DicomViewer = defineAsyncComponent(() => import('./components/DicomViewer.vue'));
interface DicomViewerHandle {
  applyPlan: (plan: import('./llm/types').SelectionPlan) => void;
  getViewportContext: () => ViewportContext | undefined;
  reset: () => void;
  scrollToInstance: (instanceNumber: number) => void;
}
function loadConfig(): ProviderConfig {
  try { return migrateProviderConfig(JSON.parse(localStorage.getItem(STORAGE_KEY) ?? 'null')); }
  catch { return createDefaultProviderConfig(); }
}

const ready = ref(false);
const initError = ref<string | null>(null);
const studyMetadata = ref<StudyMetadata | null>(null);
const imageIds = ref<string[]>([]);
const activeSeriesUID = ref('');
const activeTool = ref<ViewerTool>('WindowLevel');
const layout = ref<ViewerLayout>('1x1');
const invert = ref(false);
const flipHorizontal = ref(false);
const flipVertical = ref(false);
const cineEnabled = ref(false);
const showChat = ref(false);
const showMetadata = ref(false);
const showSeries = ref(false);
const showSettings = ref(false);
const providerConfig = ref<ProviderConfig>(loadConfig());
const viewer = ref<DicomViewerHandle | null>(null);
const chat = ref<InstanceType<typeof ChatSidebar> | null>(null);
const activeSeries = computed(() => studyMetadata.value?.series.find((series) => series.seriesInstanceUID === activeSeriesUID.value) ?? null);
const { messages, status, statusText, error, currentPlan, pipeline, startAnalysis, confirmPlan, cancelPlan, sendFollowUp, clearChat } = useLLMChat(studyMetadata, providerConfig);

function saveConfig(config: ProviderConfig): void {
  providerConfig.value = config;
  localStorage.setItem(STORAGE_KEY, JSON.stringify(config));
}
async function handleLoaded(result: LoadResult): Promise<void> {
  try {
    await initCornerstone();
    ready.value = true;
  } catch (cause) {
    initError.value = cause instanceof Error ? cause.message : 'The DICOM viewer could not initialize.';
    return;
  }
  studyMetadata.value = result.studyMetadata;
  imageIds.value = result.imageIds;
  activeSeriesUID.value = result.studyMetadata.primarySeriesUID;
  layout.value = '1x1';
  invert.value = false;
  flipHorizontal.value = false;
  flipVertical.value = false;
  cineEnabled.value = false;
}
function selectSeries(uid: string): void {
  const selected = studyMetadata.value?.series.find((series) => series.seriesInstanceUID === uid);
  if (!selected) return;
  activeSeriesUID.value = uid;
  imageIds.value = selected.slices.map((slice) => slice.imageId);
  layout.value = '1x1';
}
function openChat(): void {
  showChat.value = true;
  showMetadata.value = false;
  void nextTick(() => chat.value?.focusInput());
}
function startWithContext(hint: string, options?: { surveyMode?: boolean }): void {
  const context: ViewportContext | undefined = viewer.value?.getViewportContext();
  void startAnalysis(hint, context, options);
}
async function navigate(mapping: SliceMapping): Promise<void> {
  if (mapping.kind !== 'slice' || mapping.instanceNumber == null) return;
  const series = studyMetadata.value?.series.find((candidate) => String(candidate.seriesNumber) === mapping.seriesNumber);
  if (!series) return;
  if (series.seriesInstanceUID !== activeSeriesUID.value) selectSeries(series.seriesInstanceUID);
  await nextTick();
  viewer.value?.scrollToInstance(mapping.instanceNumber);
}

watch(currentPlan, async (plan) => {
  if (!plan || !studyMetadata.value) return;
  const target = studyMetadata.value.series.find((series) => String(series.seriesNumber) === plan.targetSeries);
  if (target && target.seriesInstanceUID !== activeSeriesUID.value) selectSeries(target.seriesInstanceUID);
  await nextTick();
  viewer.value?.applyPlan(plan);
});
watch(status, (value) => { if (value === 'awaiting-confirmation' || (value === 'idle' && messages.value.length > 0)) showChat.value = true; });
watch(layout, (value) => {
  if (value !== 'mpr' && activeTool.value === 'Crosshairs') activeTool.value = 'WindowLevel';
});

function handleKeydown(event: KeyboardEvent): void {
  const modifier = event.metaKey || event.ctrlKey;
  if (modifier && event.key.toLowerCase() === 'k' && imageIds.value.length) { event.preventDefault(); openChat(); }
  if (modifier && event.key.toLowerCase() === 'b') { event.preventDefault(); showChat.value = !showChat.value; }
  if (event.key === 'Escape') {
    if (status.value === 'awaiting-confirmation') cancelPlan();
    else if (showSettings.value) showSettings.value = false;
    else if (showChat.value) showChat.value = false;
  }
}

onMounted(async () => {
  window.addEventListener('keydown', handleKeydown);
});
onBeforeUnmount(() => window.removeEventListener('keydown', handleKeydown));
</script>

<template>
  <div class="h-full bg-neutral-950 text-neutral-100">
    <main v-if="initError" class="flex h-full items-center justify-center p-6"><p class="max-w-md rounded border border-red-800 bg-red-950/30 p-4 text-sm text-red-200">{{ initError }}</p></main>
    <LandingScreen v-else-if="imageIds.length === 0" @loaded="handleLoaded" />
    <main v-else-if="!ready" class="flex h-full items-center justify-center"><p class="text-sm text-neutral-500">Initializing DICOM viewer…</p></main>
    <div v-else class="flex h-full flex-col">
      <ToolbarPanel v-model:active-tool="activeTool" v-model:layout="layout" v-model:invert="invert" v-model:flip-horizontal="flipHorizontal" v-model:flip-vertical="flipVertical" v-model:cine-enabled="cineEnabled" :show-series="showSeries" :show-metadata="showMetadata" @reset="viewer?.reset()" @analyze="openChat" @settings="showSettings = true" @series="showSeries = !showSeries" @metadata="showMetadata = !showMetadata; showChat = false" />
      <div class="flex min-h-0 flex-1 overflow-hidden">
        <aside v-if="showSeries && studyMetadata" class="w-72 shrink-0 overflow-y-auto border-r border-neutral-700 bg-neutral-900 p-3"><div class="mb-3 flex justify-between"><h2 class="text-sm font-medium">Series</h2><button class="text-xs text-neutral-500 hover:text-white" @click="showSeries = false">Close</button></div><button v-for="series in studyMetadata.series" :key="series.seriesInstanceUID" class="mb-1 w-full rounded p-2 text-left text-xs" :class="series.seriesInstanceUID === activeSeriesUID ? 'bg-blue-600/30 text-blue-100' : 'text-neutral-400 hover:bg-neutral-800'" @click="selectSeries(series.seriesInstanceUID)"><span class="font-medium">#{{ series.seriesNumber }}</span> {{ series.seriesDescription || 'Unnamed series' }}<small class="mt-0.5 block text-neutral-500">{{ series.anatomicalPlane }} · {{ series.slices.length }} slices</small></button></aside>
        <DicomViewer ref="viewer" class="min-w-0 flex-1" :image-ids="imageIds" :series="activeSeries" :study-metadata="studyMetadata" :active-tool="activeTool" :layout="layout" :invert="invert" :flip-horizontal="flipHorizontal" :flip-vertical="flipVertical" :cine-enabled="cineEnabled" />
        <MetadataPanel v-if="showMetadata && studyMetadata" :metadata="studyMetadata" @close="showMetadata = false" />
        <ChatSidebar v-if="showChat" ref="chat" :messages="messages" :status="status" :status-text="statusText" :error="error" :pipeline="pipeline" :current-plan="currentPlan" :study-metadata="studyMetadata" @close="showChat = false" @clear="clearChat" @start="startWithContext" @follow-up="(text) => sendFollowUp(text)" @confirm="(plan) => confirmPlan(plan)" @cancel="cancelPlan" @navigate="navigate" />
      </div>
      <footer class="shrink-0 border-t border-neutral-800 px-3 py-1 text-center text-[10px] text-neutral-600">Educational and research use only · Not for clinical diagnosis</footer>
      <SettingsPanel :open="showSettings" :config="providerConfig" @close="showSettings = false" @change="saveConfig" />
    </div>
  </div>
</template>
